echo "1.00, 0.00 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 1.00  -bl 0.10 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-1.00_beta-0.10_p-vec_best_alpha -lf TrendBeta-1.00.BaseBeta-0.10 -sl -ba -ed 1024  &
echo "1.00, 0.20 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 1.00  -bl 0.30 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-1.00_beta-0.30_p-vec_best_alpha -lf TrendBeta-1.00.BaseBeta-0.30 -sl -ba -ed 1024  &
echo "1.00, 0.40 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 1.00  -bl 0.50 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-1.00_beta-0.50_p-vec_best_alpha -lf TrendBeta-1.00.BaseBeta-0.50 -sl -ba -ed 1024  &
wait
echo "1.00, 0.60 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 1.00  -bl 0.70 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-1.00_beta-0.70_p-vec_best_alpha -lf TrendBeta-1.00.BaseBeta-0.70 -sl -ba -ed 1024  &
echo "1.00, 0.80 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 1.00  -bl 0.90 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-1.00_beta-0.90_p-vec_best_alpha -lf TrendBeta-1.00.BaseBeta-0.90 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.90  -bl 0.00 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.90_beta-0.00_p-vec_best_alpha -lf TrendBeta-0.90.BaseBeta-0.00 -sl -ba -ed 1024  &
wait
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.90  -bl 0.10 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.90_beta-0.10_p-vec_best_alpha -lf TrendBeta-0.90.BaseBeta-0.10 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.90  -bl 0.20 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.90_beta-0.20_p-vec_best_alpha -lf TrendBeta-0.90.BaseBeta-0.20 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.90  -bl 0.30 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.90_beta-0.30_p-vec_best_alpha -lf TrendBeta-0.90.BaseBeta-0.30 -sl -ba -ed 1024  &
wait
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.90  -bl 0.40 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.90_beta-0.40_p-vec_best_alpha -lf TrendBeta-0.90.BaseBeta-0.40 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.90  -bl 0.50 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.90_beta-0.50_p-vec_best_alpha -lf TrendBeta-0.90.BaseBeta-0.50 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.90  -bl 0.60 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.90_beta-0.60_p-vec_best_alpha -lf TrendBeta-0.90.BaseBeta-0.60 -sl -ba -ed 1024  &
wait
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.90  -bl 0.70 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.90_beta-0.70_p-vec_best_alpha -lf TrendBeta-0.90.BaseBeta-0.70 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.90  -bl 0.80 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.90_beta-0.80_p-vec_best_alpha -lf TrendBeta-0.90.BaseBeta-0.80 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.90  -bl 0.90 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.90_beta-0.90_p-vec_best_alpha -lf TrendBeta-0.90.BaseBeta-0.90 -sl -ba -ed 1024  &
wait
echo "0.80, 0.00 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.80  -bl 0.10 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.80_beta-0.10_p-vec_best_alpha -lf TrendBeta-0.80.BaseBeta-0.10 -sl -ba -ed 1024  &
echo "0.80, 0.20 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.80  -bl 0.30 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.80_beta-0.30_p-vec_best_alpha -lf TrendBeta-0.80.BaseBeta-0.30 -sl -ba -ed 1024  &
echo "0.80, 0.40 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.80  -bl 0.50 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.80_beta-0.50_p-vec_best_alpha -lf TrendBeta-0.80.BaseBeta-0.50 -sl -ba -ed 1024  &
wait
echo "0.80, 0.60 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.80  -bl 0.70 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.80_beta-0.70_p-vec_best_alpha -lf TrendBeta-0.80.BaseBeta-0.70 -sl -ba -ed 1024  &
echo "0.80, 0.80 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.80  -bl 0.90 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.80_beta-0.90_p-vec_best_alpha -lf TrendBeta-0.80.BaseBeta-0.90 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.70  -bl 0.00 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.70_beta-0.00_p-vec_best_alpha -lf TrendBeta-0.70.BaseBeta-0.00 -sl -ba -ed 1024  &
wait
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.70  -bl 0.10 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.70_beta-0.10_p-vec_best_alpha -lf TrendBeta-0.70.BaseBeta-0.10 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.70  -bl 0.20 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.70_beta-0.20_p-vec_best_alpha -lf TrendBeta-0.70.BaseBeta-0.20 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.70  -bl 0.30 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.70_beta-0.30_p-vec_best_alpha -lf TrendBeta-0.70.BaseBeta-0.30 -sl -ba -ed 1024  &
wait
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.70  -bl 0.40 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.70_beta-0.40_p-vec_best_alpha -lf TrendBeta-0.70.BaseBeta-0.40 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.70  -bl 0.50 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.70_beta-0.50_p-vec_best_alpha -lf TrendBeta-0.70.BaseBeta-0.50 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.70  -bl 0.60 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.70_beta-0.60_p-vec_best_alpha -lf TrendBeta-0.70.BaseBeta-0.60 -sl -ba -ed 1024  &
wait
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.70  -bl 0.70 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.70_beta-0.70_p-vec_best_alpha -lf TrendBeta-0.70.BaseBeta-0.70 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.70  -bl 0.80 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.70_beta-0.80_p-vec_best_alpha -lf TrendBeta-0.70.BaseBeta-0.80 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.70  -bl 0.90 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.70_beta-0.90_p-vec_best_alpha -lf TrendBeta-0.70.BaseBeta-0.90 -sl -ba -ed 1024  &
wait
echo "0.60, 0.00 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.60  -bl 0.10 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.60_beta-0.10_p-vec_best_alpha -lf TrendBeta-0.60.BaseBeta-0.10 -sl -ba -ed 1024  &
echo "0.60, 0.20 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.60  -bl 0.30 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.60_beta-0.30_p-vec_best_alpha -lf TrendBeta-0.60.BaseBeta-0.30 -sl -ba -ed 1024  &
echo "0.60, 0.40 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.60  -bl 0.50 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.60_beta-0.50_p-vec_best_alpha -lf TrendBeta-0.60.BaseBeta-0.50 -sl -ba -ed 1024  &
wait
echo "0.60, 0.60 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.60  -bl 0.70 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.60_beta-0.70_p-vec_best_alpha -lf TrendBeta-0.60.BaseBeta-0.70 -sl -ba -ed 1024  &
echo "0.60, 0.80 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.60  -bl 0.90 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.60_beta-0.90_p-vec_best_alpha -lf TrendBeta-0.60.BaseBeta-0.90 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.50  -bl 0.00 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.50_beta-0.00_p-vec_best_alpha -lf TrendBeta-0.50.BaseBeta-0.00 -sl -ba -ed 1024  &
wait
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.50  -bl 0.10 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.50_beta-0.10_p-vec_best_alpha -lf TrendBeta-0.50.BaseBeta-0.10 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.50  -bl 0.20 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.50_beta-0.20_p-vec_best_alpha -lf TrendBeta-0.50.BaseBeta-0.20 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.50  -bl 0.30 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.50_beta-0.30_p-vec_best_alpha -lf TrendBeta-0.50.BaseBeta-0.30 -sl -ba -ed 1024  &
wait
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.50  -bl 0.40 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.50_beta-0.40_p-vec_best_alpha -lf TrendBeta-0.50.BaseBeta-0.40 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.50  -bl 0.50 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.50_beta-0.50_p-vec_best_alpha -lf TrendBeta-0.50.BaseBeta-0.50 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.50  -bl 0.60 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.50_beta-0.60_p-vec_best_alpha -lf TrendBeta-0.50.BaseBeta-0.60 -sl -ba -ed 1024  &
wait
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.50  -bl 0.70 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.50_beta-0.70_p-vec_best_alpha -lf TrendBeta-0.50.BaseBeta-0.70 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.50  -bl 0.80 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.50_beta-0.80_p-vec_best_alpha -lf TrendBeta-0.50.BaseBeta-0.80 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.50  -bl 0.90 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.50_beta-0.90_p-vec_best_alpha -lf TrendBeta-0.50.BaseBeta-0.90 -sl -ba -ed 1024  &
wait
echo "0.40, 0.00 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.40  -bl 0.10 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.40_beta-0.10_p-vec_best_alpha -lf TrendBeta-0.40.BaseBeta-0.10 -sl -ba -ed 1024  &
echo "0.40, 0.20 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.40  -bl 0.30 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.40_beta-0.30_p-vec_best_alpha -lf TrendBeta-0.40.BaseBeta-0.30 -sl -ba -ed 1024  &
echo "0.40, 0.40 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.40  -bl 0.50 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.40_beta-0.50_p-vec_best_alpha -lf TrendBeta-0.40.BaseBeta-0.50 -sl -ba -ed 1024  &
wait
echo "0.40, 0.60 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.40  -bl 0.70 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.40_beta-0.70_p-vec_best_alpha -lf TrendBeta-0.40.BaseBeta-0.70 -sl -ba -ed 1024  &
echo "0.40, 0.80 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.40  -bl 0.90 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.40_beta-0.90_p-vec_best_alpha -lf TrendBeta-0.40.BaseBeta-0.90 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.30  -bl 0.00 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.30_beta-0.00_p-vec_best_alpha -lf TrendBeta-0.30.BaseBeta-0.00 -sl -ba -ed 1024  &
wait
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.30  -bl 0.10 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.30_beta-0.10_p-vec_best_alpha -lf TrendBeta-0.30.BaseBeta-0.10 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.30  -bl 0.20 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.30_beta-0.20_p-vec_best_alpha -lf TrendBeta-0.30.BaseBeta-0.20 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.30  -bl 0.30 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.30_beta-0.30_p-vec_best_alpha -lf TrendBeta-0.30.BaseBeta-0.30 -sl -ba -ed 1024  &
wait
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.30  -bl 0.40 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.30_beta-0.40_p-vec_best_alpha -lf TrendBeta-0.30.BaseBeta-0.40 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.30  -bl 0.50 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.30_beta-0.50_p-vec_best_alpha -lf TrendBeta-0.30.BaseBeta-0.50 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.30  -bl 0.60 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.30_beta-0.60_p-vec_best_alpha -lf TrendBeta-0.30.BaseBeta-0.60 -sl -ba -ed 1024  &
wait
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.30  -bl 0.70 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.30_beta-0.70_p-vec_best_alpha -lf TrendBeta-0.30.BaseBeta-0.70 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.30  -bl 0.80 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.30_beta-0.80_p-vec_best_alpha -lf TrendBeta-0.30.BaseBeta-0.80 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.30  -bl 0.90 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.30_beta-0.90_p-vec_best_alpha -lf TrendBeta-0.30.BaseBeta-0.90 -sl -ba -ed 1024  &
wait
echo "0.20, 0.00 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.20  -bl 0.10 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.20_beta-0.10_p-vec_best_alpha -lf TrendBeta-0.20.BaseBeta-0.10 -sl -ba -ed 1024  &
echo "0.20, 0.20 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.20  -bl 0.30 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.20_beta-0.30_p-vec_best_alpha -lf TrendBeta-0.20.BaseBeta-0.30 -sl -ba -ed 1024  &
echo "0.20, 0.40 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.20  -bl 0.50 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.20_beta-0.50_p-vec_best_alpha -lf TrendBeta-0.20.BaseBeta-0.50 -sl -ba -ed 1024  &
wait
echo "0.20, 0.60 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.20  -bl 0.70 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.20_beta-0.70_p-vec_best_alpha -lf TrendBeta-0.20.BaseBeta-0.70 -sl -ba -ed 1024  &
echo "0.20, 0.80 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.20  -bl 0.90 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.20_beta-0.90_p-vec_best_alpha -lf TrendBeta-0.20.BaseBeta-0.90 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.10  -bl 0.00 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.10_beta-0.00_p-vec_best_alpha -lf TrendBeta-0.10.BaseBeta-0.00 -sl -ba -ed 1024  &
wait
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.10  -bl 0.10 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.10_beta-0.10_p-vec_best_alpha -lf TrendBeta-0.10.BaseBeta-0.10 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.10  -bl 0.20 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.10_beta-0.20_p-vec_best_alpha -lf TrendBeta-0.10.BaseBeta-0.20 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.10  -bl 0.30 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.10_beta-0.30_p-vec_best_alpha -lf TrendBeta-0.10.BaseBeta-0.30 -sl -ba -ed 1024  &
wait
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.10  -bl 0.40 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.10_beta-0.40_p-vec_best_alpha -lf TrendBeta-0.10.BaseBeta-0.40 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.10  -bl 0.50 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.10_beta-0.50_p-vec_best_alpha -lf TrendBeta-0.10.BaseBeta-0.50 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.10  -bl 0.60 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.10_beta-0.60_p-vec_best_alpha -lf TrendBeta-0.10.BaseBeta-0.60 -sl -ba -ed 1024  &
wait
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.10  -bl 0.70 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.10_beta-0.70_p-vec_best_alpha -lf TrendBeta-0.10.BaseBeta-0.70 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.10  -bl 0.80 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.10_beta-0.80_p-vec_best_alpha -lf TrendBeta-0.10.BaseBeta-0.80 -sl -ba -ed 1024  &
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.10  -bl 0.90 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.10_beta-0.90_p-vec_best_alpha -lf TrendBeta-0.10.BaseBeta-0.90 -sl -ba -ed 1024  &
wait
echo "0.00, 0.00 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.00  -bl 0.10 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.00_beta-0.10_p-vec_best_alpha -lf TrendBeta-0.00.BaseBeta-0.10 -sl -ba -ed 1024  &
echo "0.00, 0.20 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.00  -bl 0.30 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.00_beta-0.30_p-vec_best_alpha -lf TrendBeta-0.00.BaseBeta-0.30 -sl -ba -ed 1024  &
echo "0.00, 0.40 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.00  -bl 0.50 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.00_beta-0.50_p-vec_best_alpha -lf TrendBeta-0.00.BaseBeta-0.50 -sl -ba -ed 1024  &
wait
echo "0.00, 0.60 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.00  -bl 0.70 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.00_beta-0.70_p-vec_best_alpha -lf TrendBeta-0.00.BaseBeta-0.70 -sl -ba -ed 1024  &
echo "0.00, 0.80 break."
nohup /opt/miniconda3/bin/python3 -u model_2.0.py -ep ../data/Supplementary_experiment/LungCancer_dir/embedding//trend_embedding -sp ../data/Supplementary_experiment/LungCancer_dir/ -tl 0.00  -bl 0.90 -lp ../data/Supplementary_experiment/LungCancer_dir/log/TrendBeta-0.00_beta-0.90_p-vec_best_alpha -lf TrendBeta-0.00.BaseBeta-0.90 -sl -ba -ed 1024  &
echo "0.00, 1.00 break."
